CREATE TABLE IF NOT EXISTS classes (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) UNIQUE NOT NULL,
  year_group VARCHAR(255) UNIQUE NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS producers (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) UNIQUE NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS times (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(255) UNIQUE NOT NULL,
  display_order INT NOT NULL,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS events (
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  date DATE NOT NULL,
  name VARCHAR(255) NOT NULL,
  class_id INT NOT NULL,
  producer_id INT NOT NULL,
  time_id INT NOT NULL,
  topic TEXT,
  
    FOREIGN KEY (class_id)
    REFERENCES classes(id),
    FOREIGN KEY (producer_id)
    REFERENCES producers(id),
    FOREIGN KEY (time_id)
    REFERENCES times(id)
);